# all the microservices will be registered with eureka
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8769/eureka

# config server will not override default system properties of microservices
spring:
  cloud:
    config:
      override-system-properties: false

application:
  security:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000