spring:
  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls: true
        connectiontimeout: 5000
        timeout: 3000
        write-timeout: 5000

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: activation-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.personnel.filestorage
        spring.json.type.mapping: accountActivationRequest:com.personnel.filestorage.notificationservice.dto.AccountActivationConsumer

server:
  port: 8040